# Generated by Django 5.0.3 on 2024-03-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rimed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rimed',
            name='countries_found',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rimed',
            name='parts_used',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rimed',
            name='vernacular_names',
            field=models.CharField(max_length=255),
        ),
    ]
